config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'products', to: 'products#index'

  get 'basket', to: 'basket#show'

  resources :basket_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  STATES = %w[created cancelled sent]

  validates :client, presence: true
  validates :state,
            inclusion: { in: STATES }

  has_many :basket_items, dependent: :destroy

  before_save :set_subtotal

private

  def set_subtotal
    self[:subtotal] =
      basket_items.sum do |item|
        item.unit_price * item.quantity
      end
  end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

private

  def set_unit_price
    self[:unit_price] = BasketItemPriceCalculator.new(self).run
  end

  def set_total_price
    self[:total_price] = self.unit_price * quantity
  end
end

app/models/factor_discount.rb
class FactorDiscount < PricingRule
  belongs_to :product

  validates :value, presence: true
end

app/models/pricing_rule.rb
class PricingRule < ApplicationRecord
  self.abstract_class = true

  belongs_to :product

  validates :name, presence: true
  validates :enabled, inclusion:{ in: [true, false] }

  validate :valid_range_of_products_number?

  def valid_range_of_products_number?
    if max_products_number.nil? && min_products_number.nil?
      errors.add(:min_products_number, "can't be nil if max_products_number also is nil")
      return
    end
    return true if max_products_number.nil? || min_products_number.nil?

    if max_products_number < min_products_number
      errors.add(:max_products_number, 'has to be greater than min')
    end

    true
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates :code, :name, :price, presence: true

  validates :name, length: { minimum: 3 }
  validates :code,
            length: { minimum: 3 },
            format: { with: /[A-Z]{2}\d{1}/, message: 'Invalid format for code' }

  has_many :basket_items

  def pricing_rules
    FactorDiscount.where(product: self, enabled: true) +
      UnitaryPriceDiscount.where(product: self, enabled: true)
  end
end

app/models/unitary_price_discount.rb
class UnitaryPriceDiscount < PricingRule
  belongs_to :product

  validates :value, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  def show
    @basket_items = current_basket.basket_items
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket

  def create
    @basket_item = create_basket_item
    @basket.save!
    @basket_items = @basket.basket_items
    session[:basket_id] = @basket.id
  end

  def update
    @basket_item = @basket.basket_items.find(params[:id])
    @basket_item.update_attribute(:quantity, basket_item_params[:quantity])
    @basket_items = current_basket.basket_items
    @basket.save!
  end

  def destroy
    @basket_item = @basket.basket_items.find(params[:id])
    @basket_item.destroy!
    @basket_items = current_basket.basket_items
    @basket.save!
  end

private

  def basket_item_params
    params.require(:basket_item).permit(:product_id, :quantity)
  end

  def set_basket
    @basket = current_basket
  end

  def create_basket_item
    basket_item = @basket.basket_items.find_or_create_by(
      product_id: basket_item_params[:product_id]
    )
    basket_item.quantity += basket_item_params[:quantity].to_i
    basket_item.save!

    basket_item
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  def show
    @basket_items = current_basket.basket_items
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @basket_item = current_basket.basket_items.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_basket
    session_basket = Basket.find_by_id(session[:basket_id])
    return session_basket if session_basket

    Basket.create(client: "Obi wan", state: "created")
  end
end

app/views/application/_alert_success.html.erb
<strong> <%= @basket_item.quantity %></strong> '<%= @basket_item.product.name %>' added to the basket!
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

app/views/application/_alerts.html.erb
<div id="alerts-container">
  <div class="alert alert-success alert-dismissible fade show" role="alert"></div>
</div>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-xl navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%= root_path %>>HealthyProducts</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse show" id="navbarDark">
      <ul class="navbar-nav me-auto mb-2 mb-xl-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= root_path %>>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= products_path %> >Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Not so healthy products</a>
        </li>
      </ul>
      <a class="d-flex btn btn-outline-light" href=<%= basket_path %>><i class="bi bi-cart4"></i> Go cart</a>
    </div>
  </div>
</nav>

app/views/basket/_basket.html.erb
<div id="basket" class="row">
  <div id="basket-items" class="col-8">
    <%= render "basket/basket_items" %>
  </div>
  <div id="total-price" class="col-4">
    <%= render "basket/total_price" %>
  </div>
</div>

app/views/basket/_basket_item.html.erb
  <tr>
    <td class="name">
      <img src=<%= "/assets/products/#{basket_item.product.code.downcase}.jpeg" %>>
      <%= basket_item.product.name %>
    </td>
    <td><%= basket_item.product.price %> €</td>
    <%= form_with model: basket_item, local: false do |f| %>
      <%= f.hidden_field :id, value: basket_item.id %>
      <%= f.hidden_field :product_id, value: basket_item.product.id %>
      <td><%= f.number_field :quantity, value: basket_item.quantity.to_i, min: 1 %> </td>
      <td><%= basket_item.total_price %> €</td>
      <td>
        <%= f.submit "Update Basket" %>
        <%= link_to "Remove Items", basket_item, method: :delete, remote: true %>
      </td>
    <% end %>
</tr>

app/views/basket/_basket_items.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Product</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Units</th>
      <th scope="col">Subtotal</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @basket_items.each do |basket_item| %>
      <%= render partial: 'basket/basket_item', object: basket_item %>
    <% end %>
  </tbody>
</table>

app/views/basket/_total_price.html.erb
<h3> There are <%= current_basket.basket_items.sum(&:quantity) %> articles in your basket</h3>
<div class="row">
  <div class="col-8">
    TOTAL:
  </div>
  <div class="col-4 text-end">
    <%= current_basket.subtotal %> €
  </div>
</div>

app/views/basket/show.html.erb
<%= render "basket" %>

app/views/basket_items/create.js.erb
$(".alert-success").html("<%= j render 'application/alert_success' %>")
$(".alert-success").show();

app/views/basket_items/destroy.js.erb
$("#basket-items").html("<%= j render 'basket/basket_items' %>");
$("#total-price").html("<%= j render 'basket/total_price' %>");

app/views/basket_items/update.js.erb
$("#basket-items").html("<%= j render 'basket/basket_items' %>");
$("#total-price").html("<%= j render 'basket/total_price' %>");

app/views/baskets/_basket_items.html.erb
<% @basket_items.each do |item| %>
  <h3><%= item.product.name %></h3>
  <h3><%= item.product.price %></h3>
  <%= form_with model: item do |f| %>
    <%= f.hidden_field :product_id, value: item.product_id %>
    <%= f.hidden_field :quantity, value: item.quantity.to_i %>
    <%= f.submit "Update Basket" %>
    <%= link_to "Remove Items", item, method: :delete, remote: true %>
  <% end %>
  <h2>Subtotal: <% item.total_price %></h2>
<% end %>

<h3> Your current basket price is <%= current_basket.subtotal %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashRegister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
  </head>

  <body>
    <%= render 'alerts' %>
    <header>
      <%= render 'header' %>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/index.html.erb
<div class="products-container">
  <div class="row row-cols-1 row-cols-sm-3 g-3">
    <% @products.each do |product| %>
      <div class="col">
        <div class="card">
          <div class="product-image-container">
            <img src=<%= "/assets/products/#{product.code.downcase}.jpeg" %> class="card-img-top" alt="card-grid-image">
          </div>
          <div class="card-body">
            <div class="row product-card-title">
              <div class="col-8 product-card-name text-truncate"><%= product.name %></div>
              <div class="col-4 product-card-price"><%= product.price%> €</div>
            </div>
            <p class="card-text">This is a very healthy product that you should buy soon or later</p>
            <%= form_with model: @basket_item, local: false do |f| %>
              <%= f.hidden_field :product_id, value: product.id %>
              <div class="add-to-basket-group row row-cols-1">
                <%= f.number_field :quantity, class:"add-to-basket-quantity col-5", value: 1, min: 1 %>
                <%= button_tag(class:"add-to-basket-button offset-md-1 col-5") do %>
                  Add
                  <i class="bi bi-cart-plus-fill"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-sm">
	<h1>Welcome to HealthyProducts.com!</h1>
</div>